install ant
install apr-util
install autobench
install chipmunk
install cloog
install cmatrix
install coreutils
install ctags
install dnsmasq
install elixir
install erlang
install homebrew/versions/erlang-r16
install ettercap
install faac
install ffmpeg
install gcc
install geos
install ghc
install ghostscript
install gifsicle
install git
install gnu-sed
install gnupg
install gource
install graphviz
install gtk+
install hub
install imagemagick
install imapsync
install ios-sim
install libvorbis
install libyaml
install lua
install macvim
install memcached
install mitmproxy
install mobile-shell
install mongodb
install nmap
install node
install homebrew/dupes/openssh
install ossp-uuid
install python
install rbenv
install thoughtbot/formulae/rcm
install reattach-to-user-namespace
install redis
install ruby-build
install rust
install sbt
install scala
install siege
install swig
install the_silver_searcher
install nviennot/tmate/tmate
install tmux
install tree
install typesafe-activator
install vim
install watch
install wget
install wireshark
install wrk
install xctool
install zsh
