install ab
install apr-util
install coreutils
install ctags
install dnsmasq
install elixir
install erlang
install ffmpeg
install geos
install gifsicle
install gnupg
install go
install gource
install graphviz
install gtk+
install hub
install imagemagick
install ios-sim
install libspotify
install libyaml
install lua
install macvim
install memcached
install mitmproxy
install mongodb
install node
install ossp-uuid
install play
install py2cairo
install pygobject
install python
install rbenv
install reattach-to-user-namespace
install redis
install ruby-build
install rust
install sbt
install scala
install the_silver_searcher
install tmate
install tmux
install tree
install watch
install wget
install wrk
install xctool
