install ab
install coreutils
install cscope
install ctags
install dnsmasq
install elixir
install erlang
install ettercap
install ffmpeg
install geos
install gifsicle
install gnupg
install go
install gource
install graphviz
install gtk+
install hub
install imagemagick
install ios-sim
install libspotify
install libyaml
install lua
install memcached
install mitmproxy
install mongodb
install node
install openssh --with-keychain-support
install ossp-uuid
install phantomjs
install play
install py2cairo
install pygobject
install python
install rbenv
install reattach-to-user-namespace
install redis
install ruby-build
install rust
install sbt
install scala
install the_silver_searcher
install tmate
install tmux
install tree
install vim --override-system-vi
install watch
install wget
install wrk
install xctool
install zsh
