#!/usr/bin/env zsh

alias g=git
alias gs="git st"
alias gr="git read"
alias gw="git write"
alias gps="git push"
alias gpf="git pf"
alias gpl="git pull"
alias gpp="git pp"
alias grbi="git rebase -i"
alias gcm="git checkout master"
alias d=devflow
alias dc="devflow checkout"
alias :q=exit
alias :e=nvim
alias vim=nvim

alias h=heroku
alias heroku="nocorrect heroku"
alias serve="ruby -run -e httpd . -p 5000"
alias todos="glo | ag TODO: --nocolor"
alias v=vim
alias x=exit
alias k=kubectl
alias kp="kubectl --context production"
alias ks="kubectl --context sandbox"
alias kt="kubectl --context tooling"
alias kc="kubeconsole"
alias kcp="kubeconsole production"
alias kcs="kubeconsole sandbox"
alias kct="kubeconsole tooling"

alias ssh="TERM=xterm-256color ssh"

alias publickey="cat ~/.ssh/id_ed25519.pub | pbcopy"

# Default tool replacements
alias diff="diff-so-fancy"
alias cat="bat"
