#!/usr/bin/env zsh

# Enable completion
autoload -Uz compinit
compinit -u

# Show currently selected completion in menu
zstyle ':completion:*:*:*:*:*' menu select

# Show colors in completion list
zstyle ':completion:*' list-colors ''

# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/lisinge/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/lisinge/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/lisinge/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/lisinge/google-cloud-sdk/completion.zsh.inc'; fi
