#!/usr/bin/env zsh

# Enable completion
autoload -Uz compinit
compinit -u

# Show currently selected completion in menu
zstyle ':completion:*:*:*:*:*' menu select

# Show colors in completion list
zstyle ':completion:*' list-colors ''

# case-insensitive (all),partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# asdf
source /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash

# gcloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
