#!/usr/bin/env zsh

# Enable emacs bindings (makes Alt arrow keys work)
bindkey -e

# History search with arrows up/down.
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

# Make the delete key work
bindkey "\e[3~" delete-char
