#!/usr/bin/env sh

set -e
waitmessage="Wait for dependencies to install then :qa"

if [ -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
  nvim -u ~/.config/nvim/plugins.vim +PlugUpgrade +PlugUpdate! +PlugClean! +"echo '$waitmessage'"
else
  curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim -u ~/.config/nvim/plugins.vim +PlugInstall! +"echo '$waitmessage'"
fi
